### ISSUE TITLE
PyAlro login issue

### ISSUE THREAD

**Issue by itskvad** [tchellomello/python-arlo#114]
Hi,

I have PyArlo run every 30 mins to check my Arlo base station using AzureDevOps pipelines. 

Running PyArlo('username', 'passwordhere') is now giving the following error:

PyArlo('username', 'passwordhere')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\pyarlo\__init__.py", line 50, in __init__
    self.ArloMediaLibrary = ArloMediaLibrary(self,
  File "C:\Python38\lib\site-packages\pyarlo\media.py", line 29, in __init__
    self.videos = self.load(days)
  File "C:\Python38\lib\site-packages\pyarlo\media.py", line 56, in load
    data = self._session.query(url,
AttributeError: 'NoneType' object has no attribute 'get'

This error is also occurring manually on execution.

Can you advise on how I can assist with getting this resolved? 
Thanks.

**Comment by thejeffreystone** [comment]
Seeing this issue as well.

**Comment by mberry73** [comment]
Seeing the same issue. Seems Arlo has changed the api :-(

**Comment by yoooou** [comment]
I'm having the same problem.
In my case this query to "arlo.netgear.com/hmsweb/users/library" failed due to 401. But even before that, _authenticate() already failed silently where the query to "arlo.netgear.com/hmsweb/login/v2" failed due to 403.

**Comment by Zaschii** [comment]
same here

**Comment by vzlgdu** [comment]
Same for me... Help please...

**Comment by yoooou** [comment]
I have a PR #115 which works for me. My tests are very limited though. Thanks @thejeffreystone for the pointer.

**Comment by vzlgdu** [comment]
Sorry, but I don't understand what is the solution that works for you! Please can you explain better?
Thanks

**Comment by yoooou** [comment]
I don't really know what happened under the hood. I'm just following what [this PR](https://github.com/twrecked/hass-aarlo/pull/191) did. I guess we need to use a new authentication mechanism to login now so some code changes to API endpoints and requests/responses are required - see the PR for details.

**Comment by Zaschii** [comment]
yes its working with the new authentication mechanism. 
it seems that its a little bit slower, but thats not a problem for me... thank you very much. 
Just changed the 2 files const.py and __init__py.

**Comment by jwillaz** [comment]
Not to take away from the great work that has been done within this repo (I've even made small contributions once upon a time), but it has not been actively supported for a while and I keep seeing the notifications for issues and feature requests. I just wanted to share that there are other repos that are currently active and adjusting to these changes. Twrecked is managing this repo, along with plugin repos for Home Assistant, and they work very well: https://github.com/twrecked/pyaarlo

**Comment by mberry73** [comment]
Thanks for fixing it guys. Will give it a try asap.
jwillaz, I had a short look into pyaarlo. A little documentation would certainly help to get people interested i guess. :-)

**Comment by vzlgdu** [comment]
Hi, sorry, but I don't understand what are you done to fix this; I've uninstalled and reinstalled pyarlo, but the problem is the same. Please could you explain me step by step what should I do to solve? Thanks

**Comment by jwillaz** [comment]
@mberry73 you'll be able to find examples of leveraging the base package through the Home Assistant component, which has a lot of documentation, tips, and observations about the API: https://github.com/twrecked/hass-aarlo

**Comment by vzlgdu** [comment]
Hi, I’m testing your exemple; my scope is selecta base and check what is the active mode…

Do you have some sugget?

Thanks

**Comment by itskvad** [comment]
Using https://github.com/twrecked/pyaarlo/ now.

**Comment by madhatter007** [comment]
So this works?  Is the install the same for a Hassio version of HA?

**Comment by itskvad** [comment]
Not quite sure what you mean. I'm just using the python module with my own scripts.

pip install git+https://github.com/twrecked/pyaarlo
import pyaarlo

**Comment by madhatter007** [comment]
Being non-technical, I followed the below getting setup at install.
https://www.home-assistant.io/integrations/arlo/

So can drop this update above on my HA install, config, and should be good getting Arlo going again?

**Comment by zuyezheng** [comment]
Seems like the issue is that the login API is now blocking requests where user agent is `python-requests` or more specifically `('User-Agent', 'python-requests/2.24.0')` which is the default. The 1 line fix is to add something like:

```
headers['User-Agent'] = 'foobar'
```

right before this [line]( https://github.com/tchellomello/python-arlo/blob/1a8f39d57c12cbff2b4da444ce40a0538c28104b/pyarlo/__init__.py#L133).
