### ISSUE TITLE
Exception while getting mode (if in custom mode)

### ISSUE THREAD

**Issue by chaddotson** [tchellomello/python-arlo#27]
There is an issue getting the mode from base stations if you are set to schedule or custom mode.

Set custom mode before testing.

```
from logging import basicConfig, getLogger, INFO
from pyarlo import PyArlo

logger = getLogger(__name__)

logging_config = dict(level=INFO, format='[%(asctime)s - %(filename)s:%(lineno)d - %(funcName)s - %(levelname)s] %(message)s')
basicConfig(**logging_config)

arlo = PyArlo(username, password)

base = arlo.base_stations[0]
print(base.mode)
```

Results in:
```
Traceback (most recent call last):
  File "/Users/someuser/projects/arlotest/scratch.py", line 36, in <module>
    print(base.mode)
  File "/Users/someuser/.virtualenvs/python3/lib/python3.6/site-packages/pyarlo/base_station.py", line 242, in mode
    return mode['type']
KeyError: 'type'
```

**Comment by chaddotson** [comment]
to me:

This code

base_station.py
    @property
    def mode(self):
        """Return current mode."""
        resource = "modes"
        mode_event = self.publish_and_get_event(resource)
        if mode_event:
            active_mode = mode_event['properties']['active']
            modes = mode_event['properties']['modes']
            for mode in modes:
                if mode['id'] == active_mode:
                    return mode['type']

        return None


actually needs to be:

    @property
    def mode(self):
        """Return current mode."""
        resource = "modes"
        mode_event = self.publish_and_get_event(resource)
        if mode_event:
            active_mode = mode_event['properties']['active']
            modes = mode_event['properties']['modes']
            for mode in modes:
                if mode['id'] == active_mode:
                    if 'type' in mode:
                         return mode['type']

        return None

**Comment by chaddotson** [comment]
I submitted a pull request.  https://github.com/tchellomello/python-arlo/pull/28
