### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by ankurbajaj9** [tchellomello/python-arlo#97]
Can you check if your code still works with Arlo pro 2

**Comment by tchellomello** [comment]
I don't have an Arlo Pro 2 to test it. Can you perform the steps on this Readme https://github.com/tchellomello/python-arlo#usage and post the results?

**Comment by cteodorski** [comment]
When I try to run the it seems to blow up immediately:

chris@optimusprime:~/code/arlobattery$ python3 arlocheck.py
Traceback (most recent call last):
  File "arlocheck.py", line 2, in <module>
    arlo  = PyArlo('user@cccc.com', 'passwordgoeshere')
  File "/usr/local/lib/python3.5/dist-packages/pyarlo/__init__.py", line 52, in __init__
    days=days)
  File "/usr/local/lib/python3.5/dist-packages/pyarlo/media.py", line 29, in __init__
    self.videos = self.load(days)
  File "/usr/local/lib/python3.5/dist-packages/pyarlo/media.py", line 58, in load
    extra_params=params).get('data')
AttributeError: 'NoneType' object has no attribute 'get'
chris@optimusprime:~/code/arlobattery$

**Comment by denisvic** [comment]
Sam problem here. Doesn't work anymore

**Comment by chaddotson** [comment]
Works fine for me, are you using the one available on pypi?

**Comment by Zaschii** [comment]
Same problem here. Doesn't work anymore since few days.

**Comment by sspycher** [comment]
same

**Comment by chaddotson** [comment]
I haven't used the package in quite some time, but assuming their api hasn't changed substantially it maybe linked to the 2FA mandate that can be turned off again.
